version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: my-wordpress-devops-project_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: StrongDBpass!
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpass || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s

  wordpress:
    image: wordpress:php8.2-fpm
    container_name: my-wordpress-devops-project_wordpress
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: StrongDBpass!
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-config.php:/var/www/html/wp-config.php
    networks:
      - wp_net

  nginx:
    image: nginx:alpine
    container_name: my-wordpress-devops-project_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wp_net

networks:
  wp_net:
    driver: bridge

volumes:
  db_data:
  wordpress_data:
