version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: my-wordpress-devops-project_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpass || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s

  wordpress:
    image: wordpress:latest
    container_name: my-wordpress-devops-project_wordpress
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_net

  nginx:
    image: nginx:alpine
    container_name: my-wordpress-devops-project_nginx
    depends_on:
      - wordpress
    ports:
      - "8000:80"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - wp_net

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: my-wordpress-devops-project_mysqld_exporter
    restart: always
    ports:
      - "9104:9104"
    volumes:
      - ./.my.cnf:/root/.my.cnf:ro
    depends_on:
      - db
    networks:
      - wp_net

volumes:
  db_data:
  wordpress_data:

networks:
  wp_net:
