---
- name: Deploy WordPress via role
  hosts: webservers
  become: true
  vars:
    project_name: my-wordpress-devops-project

    # Ако има /opt/wordpress → ползвай го; иначе fallback към playbook_dir
    project_dir: "{{ '/opt/wordpress' if (lookup('ansible.builtin.fileglob', '/opt/wordpress', errors='ignore')) else playbook_dir + '/wordpress' }}"

    wp_site_url: "http://localhost:8000"
    wp_site_title: "My WordPress DevOps Site"
    wp_admin_user: "admin"
    wp_admin_email: "admin@example.com"
    vault_wp_admin_password: "StrongWPpass!"

  roles:
    - wp_stack
