---
- name: Deploy WordPress via role
  hosts: webservers
  become: true
  vars:
    # Пътят ще е относителен към директорията на playbook-а
    project_dir: "{{ playbook_dir }}/wordpress"
    project_name: my-wordpress-devops-project

    wp_site_url: "http://localhost:8000"
    wp_site_title: "My WordPress DevOps Site"
    wp_admin_user: "admin"
    wp_admin_email: "admin@example.com"
    vault_wp_admin_password: "StrongWPpass!"
  roles:
    - wp_stack
